name: asset_pricing
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - alembic=1.18.3=pyhcf101f3_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2026.1.4=h4c7d964_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - colorlog=6.10.1=pyh7428d3b_0
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py313hf069bd2_3
  - cpython=3.13.11=py313hd8ed1ab_100
  - cycler=0.12.1=pyhcf101f3_2
  - debugpy=1.8.19=py313h927ade5_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fonttools=4.61.1=py313hd650c13_0
  - freetype=2.14.1=h57928b3_0
  - icu=78.2=h637d24d_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - iniconfig=2.3.0=pyhd8ed1ab_0
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=9.9.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - kiwisolver=1.4.9=py313h1a38498_2
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.18=hf2c6c5f_0
  - lerc=4.0.0=h6470a55_1
  - libblas=3.11.0=5_hf2e6a31_mkl
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.11.0=5_h2a3cdd5_mkl
  - libdeflate=1.25=h51727cc_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_16
  - libgomp=15.2.0=h8ee18e1_16
  - libhwloc=2.12.2=default_h4379cf1_1000
  - libiconv=1.18=hc1393d2_2
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.11.0=5_hf9ab0e9_mkl
  - liblzma=5.8.2=hfd05255_0
  - libmpdec=4.0.0=h2466b09_0
  - libpng=1.6.54=h7351971_0
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.51.2=hf5d6505_0
  - libtiff=4.7.1=h8f73337_1
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.1=h779ef1b_1
  - libxml2-16=2.15.1=h3cfd58e_1
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.8=h4fa8253_0
  - mako=1.3.10=pyhcf101f3_1
  - markupsafe=3.0.3=py313hd650c13_0
  - matplotlib-base=3.10.8=py313he1ded55_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mizani=0.14.3=pyhd8ed1ab_0
  - mkl=2025.3.0=hac47afa_455
  - munkres=1.1.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numpy=2.4.1=py313hce7ae62_0
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.6.1=hf411b9b_1
  - optuna=4.7.0=pyhd8ed1ab_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py313hc90dcd4_2
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.2=pyhcf101f3_0
  - pillow=12.1.0=py313h38f99e1_0
  - pip=25.3=pyh145f28c_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - plotnine=0.15.2=pyhd8ed1ab_0
  - pluggy=1.6.0=pyhf9edf01_1
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.1=py313h5fd188c_0
  - pthread-stubs=0.4=h0e40799_1002
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - pytest=9.0.2=pyhcf101f3_0
  - python=3.13.11=h09917c8_100_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.13.11=h4df99d1_100
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.13=8_cp313
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32=311=py313h40c08fc_1
  - pyyaml=6.0.3=py313hd650c13_0
  - pyzmq=27.1.0=py312hbb5da91_0
  - qhull=2020.2=hc790b64_5
  - scikit-learn=1.8.0=np2py313h4ce4a18_1
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sqlalchemy=2.0.46=py313h5fd188c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.6=py313h0591002_0
  - tbb=2022.3.0=h3155e25_2
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h2c6b04d_3
  - tomli=2.4.0=pyhcf101f3_0
  - tornado=6.5.4=py313h5ea7bf4_0
  - tqdm=4.67.2=pyha7b4d00_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - ucrt=10.0.26100.0=h57928b3_0
  - vc=14.3=h41ae7f8_34
  - vc14_runtime=14.44.35208=h818238b_34
  - vcomp14=14.44.35208=h818238b_34
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - yaml=0.2.5=h6a83c73_3
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhcf101f3_1
  - zlib-ng=2.3.2=h0261ad2_1
  - zstd=1.5.7=h534d264_6
  - pip:
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - curl-cffi==0.14.0
      - dotenv==0.9.9
      - greenlet==3.3.0
      - idna==3.11
      - lxml==6.0.2
      - psycopg2-binary==2.9.11
      - pyarrow==23.0.0
      - pycparser==3.0
      - python-dotenv==1.2.1
      - requests==2.32.5
      - scipy==1.17.0
      - tidyfinance==0.2.5
      - urllib3==2.6.3
prefix: C:\Users\rcorr\anaconda3\envs\asset_pricing
